# Generated by Django 6.0.7 on 2026-08-03 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='views_count',
        ),
        migrations.AddField(
            model_name='journal',
            name='external_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of external links e.g. [{"title": "Medium", "url": "https://..."}]'),
        ),
        migrations.AddField(
            model_name='journal',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Publication Date', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='journal',
            name='read_time',
            field=models.CharField(help_text='e.g., 5 mins read', max_length=50),
        ),
    ]
